### PR TITLE
enhance example for Date/TimeField, add RELEASE.NOTES examples

### PR DESCRIPTION
**Pull request by gabi2**

### CODE REVIEW

**Comment by mvidner** [comment]
OK. What is the expectation when displaying the non-UTF-8 file? Is there a related bug to be mentioned?

**Comment by gabi2** [comment]
Sorry, I forgot to mention the related bug. It's bnc #906936 which is about the release notes which were displayed wrongly because of wrong encoding (charset=ISO-8859-1 was set instead of UTF-8).

**Comment by mvidner** [comment]
@gabi2 please mention the bug in .changes and also bump the version (otherwise the package may go unreleased for a year)

Otherwise it LGTM.

**Comment by jreidinger** [comment]
@gabi2 ping, what is status here? looks almost ready to merge

**Pull request merged**
